spring:
  application:
    name:
      "BastionServer"

mongo:
  tools:
    mongodump-path: "C:\\Program Files\\MongoDB\\mongodb-database-tools-windows-x86_64-100.12.0\\bin\\mongodump.exe"
    mongorestore-path: "C:\\Program Files\\MongoDB\\mongodb-database-tools-windows-x86_64-100.12.0\\bin\\mongorestore.exe"
    backup-files-output-path: "C:\\Users\\User\\Desktop\\BastionServerDumps"
    periodic-backup-files-output-path: "C:\\Users\\User\\Desktop\\BastionServer"
  database: "test"
time-to-autoalarm: "2000"
k-coefficient: "4"
defence-point:
  x: "49.55"
  y: "36.17"
default-password: "0123456789"